services:
  - type: web
    name: support-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python server.py
    envVars:
      - key: VK_GROUP_TOKEN
        sync: false
      - key: VK_CONFIRMATION_TOKEN
        sync: false
      - key: VK_SECRET_KEY
        sync: false
      - key: VK_GROUP_ID
        sync: false
      - key: DEVELOPER_ID
        value: 532796366
      - key: SERVER_PORT
        value: 8080
